spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/university
    username: postgres
    password: 86751899

  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss

springdoc:
  swagger-ui:
    path: /documentation/open-api.html
    url: /openapi.yaml


logging:
  file:
    name: 'd:/log/university.log'

  level:
    org.foxminded.botalov: info
    org.springframework: info
    org.hibernate: info
    javax.persistence: info

  pattern:
    console: "%d{ISO8601} |%-5level | %-16.16thread | %-32.32c | - %msg%n"
    file: "%d{ISO8601} |%-5level | %-16.16thread | %-32.32c | - %msg%n"