spring:
  datasource:
    url: jdbc:postgresql://database:5432/university
    username: postgres
    password: 86751899

springdoc:
  swagger-ui:
    path: /documentation/open-api.html
    url: /openapi.yaml

logging:
  file:
    name: '/logs/university.log'

  level:
    org.foxminded.botalov: debug
    org.springframework: debug
    org.hibernate: debug
    javax.persistence: debug

  pattern:
    console: "%d{ISO8601} |%-5level | %-16.16thread | %-32.32c | - %msg%n"
    file: "%d{ISO8601} |%-5level | %-16.16thread | %-32.32c | - %msg%n"
