DROP TABLE IF EXISTS departments CASCADE;

create table departments
(
    id   integer generated by default as identity
        constraint departments_pkey
            primary key,
    name varchar(50)
        constraint departments_name_key
            unique
);

DROP TABLE IF EXISTS courses CASCADE;

create table courses
(
    id            integer generated by default as identity
        constraint courses_pkey
            primary key,
    name          varchar(50)
        CONSTRAINT courses_name_key
            unique,
    department_id integer
        CONSTRAINT courses_department_id_fkey
            references departments
            on delete cascade
);

DROP TABLE IF EXISTS groups CASCADE;

create table groups
(
    id   integer generated by default as identity
        constraint groups_pkey
            primary key,
    name varchar(50)
        constraint groups_name_key
            unique
);

DROP TABLE IF EXISTS students CASCADE;

create table students
(
    id         integer generated by default as identity
        constraint students_pkey
            primary key,
    group_id   integer
        constraint students_group_id_fkey
            references groups
            on delete cascade,
    first_name varchar(50),
    last_name  varchar(50)
);

DROP TABLE IF EXISTS teachers CASCADE;

create table teachers
(
    id            integer generated by default as identity
        constraint teachers_pkey
            primary key,
    department_id integer
        constraint teacher_department_id_fkey
            references departments
            on delete cascade,
    first_name    varchar(50),
    last_name     varchar(50)
);

DROP TABLE IF EXISTS lessons CASCADE;

create table lessons
(
    id         integer generated by default as identity
        constraint lessons_pkey
            primary key,
    start_time timestamp,
    end_time   timestamp,
    course_id  integer
        constraint lessons_course_id_fkey
            references courses
            on delete cascade,
    teacher_id integer
        constraint lessons_teacher_id_fkey
            references teachers
            on delete cascade,
    group_id   integer
        constraint lessons_group_id_fkey
            references groups
            on delete cascade,
    classroom  integer
);

INSERT INTO departments (name)
VALUES ('department1'),
       ('department2');

INSERT INTO courses (name, department_id)
values ('course1', 1),
       ('course2', 1),
       ('course3', 2);

INSERT INTO groups (name)
VALUES ('group1'),
       ('group2'),
       ('group3');

INSERT INTO students (group_id, first_name, last_name)
VALUES (1, 'Ivan', 'Ivanov'),
       (1, 'Petr', 'Petrov'),
       (2, 'Andrey', 'Andreev');

INSERT INTO teachers (department_id, first_name, last_name)
VALUES (1, 'Ivan', 'Ivanov'),
       (1, 'Petr', 'Petrov'),
       (2, 'Andrey', 'Andreev');

INSERT INTO lessons (start_time, end_time, course_id, teacher_id, group_id, classroom)
VALUES ('2020-12-10T09:00:00.00Z', '2020-12-10T10:30:00.00Z', 1, 1, 1, 101),
       ('2020-12-10T10:30:00.00Z', '2020-12-10T12:00:00.00Z', 2, 2, 2, 102),
       ('2020-12-10T12:00:00.00Z', '2020-12-10T13:30:00.00Z', 3, 3, 3, 103),
       ('2020-12-10T13:30:00.00Z', '2020-12-10T15:00:00.00Z', 1, 1, 1, 104),
       ('2020-12-11T09:00:00.00Z', '2020-12-11T10:30:00.00Z', 2, 2, 2, 105),
       ('2020-12-11T10:30:00.00Z', '2020-12-11T12:00:00.00Z', 3, 3, 3, 106),
       ('2020-12-11T12:00:00.00Z', '2020-12-11T13:30:00.00Z', 1, 1, 1, 107);



